.welc{
    border:8px solid #0d0d0d;
width: 120rem;
display: flex;
justify-content: center;

align-items: center;
flex-direction: column;
height: 110rem;
padding-bottom: 0rem;
margin-bottom: 0rem;
   }
h3{
  font-size: 3rem;
}
h1{
  font-size: 4rem;
}
.heading{
  font-size: 5rem;
}
p{
  font-size: 2rem;
  line-height: 2rem;

}
.button{
  display: flex;
  justify-content: center;
  min-height: 10rem;
  
  gap: 1rem;
  flex-direction: column;
  align-items: center;
}
.btn{
  padding-left: 58rem;
  font-size: 2rem;

    padding-right: 50rem;
    width: 11rem;
}
.btn4{
  padding-left: 51rem;
  display: flex;
  justify-content: center;
      font-size: 2rem;
      padding-right: 48rem;
      width: 19rem;
}